apiVersion: batch/v1
kind: CronJob
metadata:
  name: finance-sync
spec:
  schedule: "0 2,8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: app-config
              configMap:
                name: app-config
            - name: app-secrets
              secret:
                secretName: app-secrets
            - name: app-pv
              persistentVolumeClaim:
                claimName: app-pvc
          containers:
          - name: finance-sync
            image: cjwrites/finance_sync:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - poetry run python main.py
            volumeMounts:
              - name: app-config
                mountPath: /app/res
              - name: app-secrets
                mountPath: /app/secrets
              - name: app-pv
                mountPath: "/app/data"
          restartPolicy: Never
          