apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cron.yaml

configMapGenerator:
  - name: app-config
    files:
      - res/categories.json
secretGenerator:
  - name: app-secrets
    files:
      - secrets/credentials.json
      - secrets/token.json