apiVersion: v1
# Doesnt work for now. Oh well
kind: PersistentVolume
metadata:
  name: app-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Mi
  hostPath:
    path: /data/finance-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi
